In [188]:
""" This file describes code assignment2a for COMP10200.
    Chengkang Huang, 000787205, Mohawk College, 2022
"""

# Import the libraries
import csv
import numpy as np
from matplotlib import pyplot as plt

In [189]:
def readCSV(fileName: str):
    """ Read the .csv file and combine all data into a large dataset

    Read .csv file from current folder, append each record data into each
    feature name array, finally combine them into a new large numpy array.

    Arg:
        fileName(str): The string that contain the .csv file location.

    Return:
        A new large numpy array that contain all record from .csv file.
        Ex:
        np.array([UserId, Art_galleries, Dance_clubs, Juice_bars, Restaurants, Museums, Resorts, Picnic_spots, Beaches, Theaters, Religious_institutions, labels])

    Rasies:
        File Error: File not exist or not in the correct location.
        Read Row Error: Something wrong with the record data in the .csv file.
    """
    pass

    UserId = []
    Art_galleries = []
    Dance_clubs = []
    Juice_bars = []
    Restaurants = []
    Museums = []
    Resorts = []
    Picnic_spots = []
    Beaches = []
    Theaters = []
    Religious_institutions = []
    labels = []

    try:
        with open(fileName) as file:
            reader = csv.DictReader(file)
            for row in reader:
                try:
                    UserId.append(int(row['UserID']))
                    Art_galleries.append(float(row['Art_galleries']))
                    Dance_clubs.append(float(row['Dance_clubs']))
                    Juice_bars.append(float(row['Juice_bars']))
                    Restaurants.append(float(row['Restaurants']))
                    Museums.append(float(row['Museums']))
                    Resorts.append(float(row['Resorts']))
                    Picnic_spots.append(float(row['Picnic_spots']))
                    Beaches.append(float(row['Beaches']))
                    Theaters.append(float(row['Theaters']))
                    Religious_institutions.append(
                        float(row['Religious_institutions']))
                    labels.append(str(evaluation((float(row['Art_galleries']) +
                                                  float(row['Dance_clubs']) +
                                                  float(row['Juice_bars']) +
                                                  float(row['Restaurants']) +
                                                  float(row['Museums']) +
                                                  float(row['Resorts']) +
                                                  float(row['Picnic_spots']) +
                                                  float(row['Beaches']) +
                                                  float(row['Theaters']) +
                                                  float(row['Religious_institutions'])) / 10)))
                except:
                    print("Read row error")
            print("Successfully read the data")
    except:
        print("Open file error")

    return np.array([labels]), np.array([Art_galleries, Dance_clubs, Juice_bars, Restaurants, Museums, Resorts, Picnic_spots, Beaches, Theaters, Religious_institutions])


def evaluation(score: float) -> str:
    """ Check the score from the data and give back the label

    Base on the rating score, compare with the enum "Rating" to set
    the label for each record.

    Arg:
        score(float): The number from each record.

    Return:
        resultStr(str): The label base on different input.

    """
    pass

    resultStr = ""
    if 0.0 <= score <= 1.0:
        resultStr = "Terrible"
    elif 1.0 < score <= 2.0:
        resultStr = "Poor"
    elif 2.0 < score <= 3.0:
        resultStr = "Average"
    elif 3.0 < score <= 4.0:
        resultStr = "VeryGood"
    elif 4.0 < score <= 5.0:
        resultStr = "Excellent"
    else:
        resultStr = "No rating scores"
    return resultStr

In [190]:
print("\n\n***** Look in the code for COMP10200 code assignment2a *****\n\n")
# Code start here

# Read data from .csv file
fileName = "tripadvisor_review.csv"
label, data = readCSV(fileName)

# Randomly split 75% data for training, then the rest 25% data for testing
trainingData_indexes = np.random.choice(data.shape[1], size=round(data.shape[1] * 0.75), replace=False)
trainingData = data[:, trainingData_indexes]
trainingLabel = label[:, trainingData_indexes]
testingData_indexes = np.delete(np.arange(data.shape[1]), trainingData_indexes)
testingData = data[:, testingData_indexes]
testingLabel = label[:, testingData_indexes]




***** Look in the code for COMP10200 code assignment2a *****


Successfully read the data


In [191]:
testingData[:, :1]

array([[0.93],
       [1.8 ],
       [2.29],
       [0.62],
       [0.8 ],
       [2.42],
       [3.19],
       [2.79],
       [1.82],
       [2.42]])

In [192]:
trainingData[:, :1] - testingData[:, :1]

array([[-0.35],
       [-0.56],
       [-0.34],
       [-0.01],
       [ 0.42],
       [-0.56],
       [ 0.  ],
       [-0.07],
       [-0.12],
       [-0.04]])

In [193]:
a = trainingData - testingData[:, :1]
print(a.shape)
print(a)

(10, 735)
[[-0.35  0.09  0.09 ... -0.23 -0.23 -0.23]
 [-0.56 -0.6  -0.48 ...  0.44 -0.92 -0.16]
 [-0.34 -1.99 -0.71 ...  0.03  0.37  0.17]
 ...
 [-0.07  0.14 -0.04 ... -0.14  0.09  0.16]
 [-0.12 -0.48 -0.44 ... -0.54 -0.28  0.07]
 [-0.04  1.    0.8  ...  0.   -0.02 -0.04]]


In [194]:
b = ((trainingData - testingData[:, 1:2]) ** 2)
b

array([[1.0240e-01, 1.4400e-02, 1.4400e-02, ..., 4.0000e-02, 4.0000e-02,
        4.0000e-02],
       [1.4400e-02, 2.5600e-02, 1.6000e-03, ..., 7.7440e-01, 2.3040e-01,
        7.8400e-02],
       [2.8561e+00, 1.6000e-03, 1.7424e+00, ..., 4.2436e+00, 5.7600e+00,
        4.8400e+00],
       ...,
       [3.6000e-03, 7.2900e-02, 8.1000e-03, ..., 1.0000e-04, 4.8400e-02,
        8.4100e-02],
       [2.3040e-01, 1.4400e-02, 2.5600e-02, ..., 3.6000e-03, 1.0240e-01,
        4.4890e-01],
       [7.0560e-01, 4.0000e-02, 0.0000e+00, ..., 6.4000e-01, 6.7240e-01,
        7.0560e-01]])

In [195]:
distanceArray = np.sqrt(((trainingData - testingData[:, :1]) ** 2).sum(axis=0))
distanceArray

array([1.03087342, 2.44879562, 1.7824702 , 1.60387032, 2.34899979,
       0.71644958, 1.5467385 , 2.02817652, 2.56203044, 2.2570556 ,
       1.46816212, 1.25355494, 2.4650355 , 2.88249892, 2.69141227,
       2.543875  , 1.84152111, 1.10072703, 1.21622366, 2.30423523,
       1.48512626, 1.79220535, 1.60956516, 2.19963633, 1.60695364,
       0.72958893, 1.82321145, 1.32249764, 0.96145723, 2.40503638,
       1.54440927, 1.29108482, 2.18043574, 2.3664953 , 1.64553943,
       1.17571255, 1.46526448, 1.72597798, 1.17388245, 2.77712081,
       1.06920531, 2.15520301, 1.04288063, 3.3074915 , 1.80474375,
       1.80975136, 1.7302023 , 0.6374951 , 2.75118156, 2.04191087,
       2.36351433, 0.62992063, 1.46775339, 1.45969175, 2.56602806,
       2.04337955, 3.07484959, 2.23691752, 2.22950667, 2.56848204,
       0.95801879, 2.36529068, 1.84301384, 2.17529308, 1.17690271,
       1.1572813 , 2.72249885, 1.42523682, 2.24750973, 1.18063542,
       0.93680307, 2.40147871, 1.49733096, 2.71976102, 2.35212

In [196]:
min_dist_point = trainingLabel[:, distanceArray.argmin()]
min_dist_point

array(['Poor'], dtype='<U7')

In [198]:
trainingData[:, distanceArray.argsort()[:3]]

array([[0.9 , 0.67, 0.9 ],
       [1.84, 1.4 , 1.44],
       [2.46, 2.32, 2.34],
       [0.67, 0.55, 0.55],
       [0.86, 0.94, 0.94],
       [2.36, 2.38, 2.14],
       [3.2 , 3.19, 3.19],
       [2.9 , 2.71, 2.79],
       [1.86, 1.5 , 1.79],
       [2.4 , 2.38, 2.82]])

In [ ]:
len(testingData[0])

245