#### Array Programming with Numpy

In [3]:
import numpy as np

In [53]:
l1 = [10, 'str', 30, 40]
np.array(l1)
len(np.array(l1))

4

In [10]:
l2 = [1, 2, 3, 4]
a1 = np.array(l2)

In [12]:
type(a1)

numpy.ndarray

In [29]:
n2 = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
n2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [91]:
n3 = np.zeros((5, 4))
n3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
n4 = np.full((3, 3), 55)
n4

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [21]:
n5 = np.arange(10, 50)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [27]:
n6 = np.random.randint(100, 200, 5)
n6

array([103, 123, 100, 149, 141])

In [26]:
n6.shape

(5,)

####Related Array

In [43]:
scores = np.random.randint(100, 200, 5)
scores

array([151, 133, 134, 151, 127])

In [44]:
names = np.array(["ann", "jack", "mark", "joe", "tine"])
names

array(['ann', 'jack', 'mark', 'joe', 'tine'], dtype='<U4')

In [45]:
ages = np.array([40, 35, 25, 27, 33])
ages

array([40, 35, 25, 27, 33])

In [47]:
scores[names=="ann"]

array([151])

In [48]:
names[scores > 150]

array(['ann', 'joe'], dtype='<U4')

In [49]:
ages[scores > 150]

array([40, 27])

In [50]:
ages[scores > 150].mean()

33.5

In [52]:
# find the player with max score
names[scores.argmax()]

'ann'

In [53]:
names[scores.argmin()]

'tine'

In [55]:
# Sort the array base on 
names.argsort()

array([0, 1, 3, 2, 4], dtype=int64)

In [57]:
names[names.argsort()]

array(['ann', 'jack', 'joe', 'mark', 'tine'], dtype='<U4')

In [58]:
ages[names.argsort()]

array([40, 35, 27, 25, 33])

In [59]:
scores[names.argsort()]

array([151, 133, 151, 134, 127])

In [61]:
scores.argsort()[2:4]

array([2, 0], dtype=int64)

In [62]:
scores.argsort()[:4]

array([4, 1, 2, 0], dtype=int64)

In [63]:
scores.argsort()[::-1]

array([3, 0, 2, 1, 4], dtype=int64)

In [64]:
names[scores.argmax()]

'ann'

In [71]:
nameSet = {'Alicia', 'Khadija', 'Lachlan', 'Lee', 'Margie'}
nameSet

{'Alicia', 'Khadija', 'Lachlan', 'Lee', 'Margie'}

In [75]:
nameList1 = np.array(set(('Alicia', 'Khadija', 'Lachlan', 'Lee', 'Margie')))
nameList1

array({'Margie', 'Lachlan', 'Khadija', 'Alicia', 'Lee'}, dtype=object)

In [90]:
nameList1.item()

{'Alicia', 'Khadija', 'Lachlan', 'Lee', 'Margie'}

In [83]:
for n in nameList1.item():
    print(n)

Margie
Lachlan
Khadija
Alicia
Lee


In [34]:
names = np.array(['Alicia', 'Khadija', 'Lachlan', 'Lee', 'Margie'])
names

array(['Alicia', 'Khadija', 'Lachlan', 'Lee', 'Margie'], dtype='<U7')

In [35]:
times = np.array([
    [0.127, 0.257, 0.112, 0.239, 0.113, 0.239, 0.129, 0.239, 0.128], 
    [0.43, 0.447, 0.432, 0.433, 0.383, 0.4, 0.224, 0.256, 0.241], 
    [0.128, 0.32, 0.112, 0.288, 0.111, 0.273, 0.128, 0.255, 0.129], 
    [0.112, 0.112, 0.113, 0.111, 0.127, 0.114, 0.132, 0.107, 0.112], 
    [0.127, 0.241, 0.112, 0.049, 0.112, 0.239, 0.128, 0.448, 0.111]])
times

array([[0.127, 0.257, 0.112, 0.239, 0.113, 0.239, 0.129, 0.239, 0.128],
       [0.43 , 0.447, 0.432, 0.433, 0.383, 0.4  , 0.224, 0.256, 0.241],
       [0.128, 0.32 , 0.112, 0.288, 0.111, 0.273, 0.128, 0.255, 0.129],
       [0.112, 0.112, 0.113, 0.111, 0.127, 0.114, 0.132, 0.107, 0.112],
       [0.127, 0.241, 0.112, 0.049, 0.112, 0.239, 0.128, 0.448, 0.111]])

In [36]:
meanTimes = np.zeros((5))
singleFast = np.zeros((5))
singleSlow = np.zeros((5))
for i in range(len(times)):
    meanTimes[i] = times[i].mean()
    singleFast[i] = times[i].min()
    singleSlow[i] = times[i].max()
print(meanTimes)
print(singleFast)
print(singleSlow)

[0.17588889 0.36066667 0.19377778 0.11555556 0.17411111]
[0.112 0.224 0.111 0.107 0.049]
[0.257 0.447 0.32  0.132 0.448]


In [37]:
print(names[names.argsort()])
print(meanTimes[names.argsort()])
print("Fastest Average Time: " + str(meanTimes.min()) + " by " + names[meanTimes.argmin()])
print("Slowest Average Time: " + str(meanTimes.max()) + " by " + names[meanTimes.argmax()])
print("Fastest Single Time: " + str(singleFast.min()) + " by " + names[singleFast.argmin()])
print("Slowest Single Time: " + str(singleSlow.max()) + " by " + names[singleSlow.argmax()])

['Alicia' 'Khadija' 'Lachlan' 'Lee' 'Margie']
[0.17588889 0.36066667 0.19377778 0.11555556 0.17411111]
Fastest Average Time: 0.11555555555555556 by Lee
Slowest Average Time: 0.3606666666666667 by Khadija
Fastest Single Time: 0.049 by Margie
Slowest Single Time: 0.448 by Margie


In [52]:
print("Names: {}".format(names[names.argsort()]))
print("Mean times: {}".format(times[names.argsort()].mean(axis = 1).round(3)))
print("Fastest Average Time: {0:.3f} by {1}".format(np.mean(times, axis = 1).min(), names[np.average(times, axis = 1).argmin()]))
print("Slowest Average Time: {0:.3f} by {1}".format(np.mean(times, axis = 1).max(), names[np.average(times, axis = 1).argmax()]))
print("Fastest Single Time: {0:.3f} by {1}".format(np.min(times, axis = 1).min(), names[np.min(times, axis = 1).argmin()]))
print("Slowest Single Time: {0:.3f} by {1}".format(np.max(times, axis = 1).max(), names[np.max(times, axis = 1).argmax()]))

Names: ['Alicia' 'Khadija' 'Lachlan' 'Lee' 'Margie']
Mean times: [0.176 0.361 0.194 0.116 0.174]
Fastest Average Time: 0.116 by Lee
Slowest Average Time: 0.361 by Khadija
Fastest Single Time: 0.049 by Margie
Slowest Single Time: 0.448 by Margie
