In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import numpy as np

In [2]:
dataset = datasets.load_breast_cancer()

In [3]:
dataset.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [4]:
dataset.target_names

array(['malignant', 'benign'], dtype='<U9')

In [5]:
gnb = GaussianNB()

In [6]:
gnb.fit(dataset.data, dataset.target)

GaussianNB()

In [7]:
y_pred = gnb.predict(dataset.data)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

In [8]:
dataset.data.shape[0]

569

In [9]:
# Compare targets with the predictions
(dataset.target != y_pred).sum()

33

In [10]:
print("Number of mislabeled points out of a total", dataset.data.shape[0], "points:", (dataset.target != y_pred).sum())

Number of mislabeled points out of a total 569 points: 33


In [11]:
gnb.predict_proba(dataset.data)

array([[1.00000000e+000, 1.08444664e-144],
       [1.00000000e+000, 2.04018399e-052],
       [1.00000000e+000, 4.74993545e-066],
       ...,
       [1.00000000e+000, 3.57502498e-011],
       [1.00000000e+000, 5.13525095e-108],
       [4.52927015e-016, 1.00000000e+000]])

In [12]:
probs = gnb.predict_proba(dataset.data).max(axis = 1)
probs

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       0.99993214, 1.        , 0.9999987 , 1.        , 1.        ,
       0.99154257, 1.        , 1.        , 0.66230831, 1.        ,
       1.        , 0.9999683 , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.98256399, 1.        , 1.        , 0.54899365,
       1.        , 0.99999963, 1.        , 0.84677485, 0.99861055,
       1.        , 1.        , 0.99428068, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.92044274,
       1.        , 1.        , 0.99999998, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.99890919,
       0.99998515, 1.        , 1.        , 0.99994213, 1.        ,
       1.        , 1.        , 1.        , 0.99999326, 1.     

In [13]:
low_confidence = probs < 0.9
low_confidence

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,